version: "3.3"
services:
  python-code:
    build:
      context: .
    volumes:
      - ./:/working/app
    env_file:
      - secret.env

  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - secret.env
    ports:
      - "3306:3306"
    volumes:
      - bia-sql-data:/var/lib/mysql

volumes:
  bia-sql-data: