version: "3.3"
services:
  python-code:
    build:
      context: .
    volumes:
      - ./:/working/app
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bia1234
    ports:
      - "3306:3306"
    volumes:
      - bia-sql-data:/var/lib/mysql

volumes:
  bia-sql-data: